### ISSUE TITLE
No completed items?

### ISSUE THREAD

**Issue by NeedsLoomis** [romgrk/node-todoist#23]
Heyo, great module!

Sync doesn't seem to grab completed items.  Is there an option for this I'm missing?

**Comment by NeedsLoomis** [comment]
Update, if I mark an item checked through the API, its retrieved by sync(), but if I manually check it, it won't show up.

**Comment by romgrk** [comment]
It seems the API has a special route for that: https://developer.todoist.com/sync/v8/#get-all-completed-items

I'll close because it doesn't seem to be an issue in this module.

**Comment by daviscodesbugs** [comment]
It would be nice to include the ability to fetch completed items.
@romgrk  If I were to create a PR, would it be better as a parameter on `.sync()` (such as `.sync(['completedItems'])`), or a method on `.items` (such as `.items.getCompleted()`)?

**Comment by romgrk** [comment]
@daviscodesbugs it depends, the package API mirrors closely the REST API, so it would depend on that.
