### ISSUE TITLE
HTTPError: Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by jnpatrick99** [romgrk/node-todoist#43]
Just installed the npm module, added my API key and ran the example provided in the readme.

Whatever I tried to do I receive a ``HTTPError: Response code 403 (Forbidden)`` error.

**Comment by romgrk** [comment]
Can't really help, the authentication happens on todoist's side. I'd say try to generate a new API key. If that doesn't work, try using another todoist library/tool with the new key, so we know where is the issue. If the key doesn't work anywhere, contact their support.

**Comment by jnpatrick99** [comment]
Generating new API key didn't help unfortunately. Todoist support won't answer. I tried another cli and there's the same problem that users are experiencing: https://github.com/sachaos/todoist/issues/201

**Comment by anastasiuspernat** [comment]
I duplicate my answer to the issue in the Go repo here just in case:

Todoist authentication seems to have changed. This is what happened: https://groups.google.com/a/doist.com/g/todoist-api/c/sqrGTtCr-4A

The API must pass token in Headers instead of a parameter.

**Comment by PieterDePauw** [comment]
This issue has been fixed in https://github.com/romgrk/node-todoist/commit/6d3c3f80de06b06740a391c906d5887fff1ba95b
